FROM adelith/work:face-recognition

WORKDIR /face-master

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .


RUN go build -o face-master /face-master/example/simple-face-recognizer/main.go

RUN chmod +x /face-master

CMD [ "./face-master" ]